services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=${TZ}
      - INSECURE=true
      - INIT_ENABLED=true
      - INIT_USERNAME=${INIT_USERNAME}
      - INIT_PASSWORD=${INIT_PASSWORD}
      - INIT_HOST=${WG_HOST}
      - INIT_PORT=${WG_PORT}
      - INIT_DNS=${WG_DNS}
      - INIT_ALLOWED_IPS=${WG_ALLOWED_IPS}
      - DISABLE_IPV6=true
    volumes:
      - ./data:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "${WG_PORT}:51820/udp"
      - "${UI_PORT}:51821/tcp"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
